version: '3.8'

services:
  nest-app:
    build: .
    image: nest-app:1.0
    container_name: nest-app
    networks:
      vue-nest-network:
        ipv4_address: 172.25.0.2
#     second-test-network:
#       ipv4_address: 172.26.0.2
    ports:
      - 3000:3000
    volumes:
      - .:/home/nest-app
    depends_on:
      mysqldb:
        condition: service_healthy

  mysqldb:
    image: mysql:8.0
    container_name: nest-app-mysqldb
    restart: always
    ports:
      - 3308:3306
#       3308 => access db from host machine: localhost:3308
#       3306 => connect containers within isolated docker network: nest-app-mysqldb:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysql-root-superuser-password
      - MYSQL_DATABASE=nest-app-db
    volumes:
      - mysql-nest-app-data:/var/lib/mysql                               # named volume
    networks:
      vue-nest-network:
        ipv4_address: 172.25.0.3
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "nest-app-mysqldb"]
      interval: 2s
      timeout: 20s
      retries: 10

  nginx:
    image: nginx:1.21.5-alpine
    container_name: nest-app-nginx
    restart: unless-stopped
    ports: 
      - 80:80
    volumes:
      - ./volumes/nginx/usr-share-nginx-html:/usr/share/nginx/html         # host volume
      - ./volumes/nginx/etc-nginx:/etc/nginx                               # host volume
#     - usr-share-nginx-html:/usr/share/nginx/html                         # named volume
#     - etc-nginx:/etc/nginx                                               # named volume
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  mysql-nest-app-data:
    name: mysql-nest-app-data
# etc-nginx:                                                              # named volume settings
#   name: etc-nginx
#   driver: local
#   driver_opts:
#     type: none
#     o: bind
#     device: /home/named_volumes/etc-nginx                               # set named volume save directory
# usr-share-nginx-html:                                                   # named volume settings
#   name: usr-share-nginx-html
#   driver: local
#   driver_opts:
#     type: none
#     o: bind
#     device: /home/named_volumes/usr-share-nginx-html                    # set named volume save directory

networks:
  vue-nest-network:
    name: vue-nest-network
    driver: bridge
#   enable_ipv6: false
    ipam:
#     driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1

# second-test-network:
#   name: second-test-network
#   driver: bridge
#   ipam:
#     config:
#       - subnet: 172.26.0.0/16
#         gateway: 172.26.0.1