version: '3.8'

services:
  nest-app:
    build: .
    image: nest-app:1.0
    container_name: nest-app
    networks:
      vue-nest-network:
        ipv4_address: 172.25.0.2
#     second-test-network:
#       ipv4_address: 172.26.0.2
    ports:
      - 3000:3000
    volumes:
      - .:/home/nest-app
    depends_on:
      mysqldb:
        condition: service_healthy

  mysqldb:
    image: mysql:8.0
    container_name: nest-app-mysqldb
    restart: always
    ports:
      - 3308:3306
#       3308 => access db from host machine: localhost:3308
#       3306 => connect containers within isolated docker network: nest-app-mysqldb:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysql-root-superuser-password
      - MYSQL_DATABASE=nest-app-db
    volumes:
      - mysql-nest-app-data:/var/lib/mysql                               # named volume
    networks:
      vue-nest-network:
        ipv4_address: 172.25.0.3
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "nest-app-mysqldb"]
      interval: 2s
      timeout: 20s
      retries: 10

  nginx:
    image: nginx:1.21.5-alpine
    container_name: nest-app-nginx
    restart: unless-stopped
#   user: $USER                  # docker run --user [username]            # on new named volume creation
    ports: 
      - 80:80
    volumes:
      - ./volumes/nginx/usr-share-nginx-html:/usr/share/nginx/html         # host volume
      - etc-nginx:/etc/nginx                                               # named volume
    extra_hosts:
      # Add host-container:container-gateway to directory /etc/hosts inside the container
      # Also Docker automatically adds host-host:host-gateway on host machine when installed
      # From official doc: special DNS name which resolves to the internal IP address used by the host
        - host.docker.internal:host-gateway
      # For this to work we have to update /etc/hosts directly on host machine as well:
      # Windows C:\Windows\System32\drivers\etc
      # DUE TO DOCKER IT IS TWO LEVEL HOST BINDING
      # - vue-nest-app.com:host-gateway
      # - www.vue-nest-app.com:host-gateway
    networks:
      vue-nest-network:
        ipv4_address: 172.25.0.4
#   network_mode: none             # docker run --network none => no network interaction at all
#   If no network is specified for a service then [projectname]_default network will be created
#   to connect the service

volumes:
  mysql-nest-app-data:
    name: mysql-nest-app-data
  etc-nginx:                                             # named volume settings
    name: etc-nginx
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/nginx/etc-nginx                  # set relative | absolute named volume save directory path

networks:
  vue-nest-network:
    name: vue-nest-network
    driver: bridge
#   enable_ipv6: false
    ipam:
#     driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1

# second-test-network:
#   name: second-test-network
#   driver: bridge
#   ipam:
#     config:
#       - subnet: 172.26.0.0/16
#         gateway: 172.26.0.1